using Test
using SHA
using JSON3
using FusionConceptAI

const _MIG_U0 = UnitSignature()
const _MIG_LEN = UnitSignature((0, 1, 0, 0, 0, 0, 0))

function _mig_bounds(lo, hi; unit=_MIG_U0)
    QuantityIntervalV1(ExactFiniteIntervalV1(lo, hi, false), unit)
end
function _mig_root(site, position, input, output)
    SpatialProgramRootRefV1(FieldOperatorSiteRefV1(site), position, input, output)
end
function _mig_values()
    cc = chart_coordinate_type_v1(); ambient = normalized_ambient_coordinate_type_v1(); metric = normalized_covariant_metric_type_v1()
    refs = Any[SpatialSupportRefV1("状态\0🚀"), ChartRefV1("é"), CoordinateFrameRefV1("é"), PhaseFieldRefV1("phase"),
        ImplicitFieldTermRefV1("implicit"), PotentialFieldRefV1("potential"), SourceFieldRefV1("source"),
        InterfaceOperatorRefV1("interface"), GeometryEvolutionRefV1("evo"), FieldParameterRefV1("param"),
        SourceBudgetRefV1("budget"), TopologyEventRefV1("topology"),
        SpatialMultiIndex3V1(typemax(Int64), typemin(Int64), -17),
        ExactSpatialVector3V1((1//3, -7//11, 13//17), UnitSignature((1, 0, -1, 0, 0, 0, 0)))]
    push!(refs, FieldParameterGeneV1(FieldParameterRefV1("linear\"x"), _MIG_U0,
        ParameterTransformSpecV1(transform_linear), _mig_bounds(-2, 4), -0.0))
    push!(refs, FieldParameterGeneV1(FieldParameterRefV1("log"), _MIG_U0,
        ParameterTransformSpecV1(transform_log), _mig_bounds(1, 100), 0.25))
    push!(refs, FieldParameterGeneV1(FieldParameterRefV1("signed"), _MIG_U0,
        ParameterTransformSpecV1(transform_signed_log, NonnegativeQuantityV1(1, _MIG_U0)), _mig_bounds(-3, 3), -0.5))
    axis1 = PeriodicAxisV1(1, NonnegativeQuantityV1(7, _MIG_U0)); axis3 = PeriodicAxisV1(3, NonnegativeQuantityV1(7, _MIG_U0))
    chart_a = CoordinateChartGeneV1(ChartRefV1("chart\"b"), CoordinateFrameRefV1("frame-b"),
        (_mig_bounds(-2, 5), _mig_bounds(-3, 4), _mig_bounds(-1, 6)), (axis3, axis1),
        _mig_root("coord-b", 2, cc, ambient), _mig_root("metric-b", 7, cc, metric))
    chart_b = CoordinateChartGeneV1(ChartRefV1("chart-a"), CoordinateFrameRefV1("frame-a"),
        (_mig_bounds(-2, 5), _mig_bounds(-3, 4), _mig_bounds(-1, 6)), (),
        _mig_root("coord-a", 2, cc, ambient), _mig_root("metric-a", 7, cc, metric))
    transition = ChartTransitionMapGeneV1(ChartRefV1("chart-a"), ChartRefV1("chart\"b"), _mig_root("transition", 9, cc, cc))
    support = SpatialSupportGeneV1(SpatialSupportRefV1("support\0"), 3,
        (CoordinateFrameRefV1("frame-b"), CoordinateFrameRefV1("frame-a")), (chart_a, chart_b), (transition,),
        NonnegativeQuantityV1(2, _MIG_LEN))
    (refs..., FieldOperatorSiteRefV1("site\0"), _mig_root("root\0", 11, cc, ambient), _mig_root("root-metric", 12, cc, metric), axis1, chart_a, transition, support)
end

@testset "G2 canonical migration fixed goldens and closed writer" begin
    # Frozen from detached baseline bc5f61da4b3ce7ecf746a304c7396e466626634a;
    # these bytes are never regenerated by the implementation under test.
    values = _mig_values()
    lines = readlines(joinpath(@__DIR__, "fixtures", "g2_migration_baseline.jsonl"))
    @test fieldcount(typeof(values)) == 24
    @test length(lines) == 48
    @test length(lines) == 2 * fieldcount(typeof(values))
    i = 1
    while i <= fieldcount(typeof(values))
        value = getfield(values, i)
        @test JSON3.read(lines[2i - 1]) !== nothing
        @test canonical_json(value) === lines[2i - 1]
        @test canonical_hash(value).value === lines[2i]
        i += 1
    end

    @testset "shared float writer fixed text and SHA" begin
        cases = ((Float64(0.0), "0.0", "8aed642bf5118b9d3c859bd4be35ecac75b6e873cce34e7b6f554b06f75550d7"),
            (Float64(-0.0), "0.0", "8aed642bf5118b9d3c859bd4be35ecac75b6e873cce34e7b6f554b06f75550d7"),
            (Float64(0.25), "0.25", "a30a043314fa89294fa2c1c989a01fbb5329e5c085a5c5a8d27317656de24ae0"),
            (nextfloat(0.0), "5.0e-324", "c5a1c1cc25110bf3657a3dd6c1a3a088d062041b703c62717011b8dca6b8f084"),
            (floatmax(Float64), "1.7976931348623157e308", "217ab4b30c6f536b285884e38da73315e3c6e694910dbbd5ae36f396b6f835bb"))
        for case in cases
            io = FusionConceptAI._ccbw_new(); FusionConceptAI._ccbw_float!(io, case[1])
            @test FusionConceptAI._ccbw_finish(io) === case[2]
            @test bytes2hex(sha256(Vector{UInt8}(codeunits(case[2])))) === case[3]
            @test FusionConceptAI._ccbw_hash_bytes(case[2]).value === case[3]
        end
    end

    @testset "fresh process broad dispatch pollution" begin
        function probe(definition, trigger)
            script = raw"""
            using FusionConceptAI
            using SHA
            const HIT = Ref(false)
            u0 = UnitSignature(); ulen = UnitSignature((0,1,0,0,0,0,0))
            cc = chart_coordinate_type_v1(); ambient = normalized_ambient_coordinate_type_v1(); metric = normalized_covariant_metric_type_v1()
            root(s,p,i,o) = SpatialProgramRootRefV1(FieldOperatorSiteRefV1(s),p,i,o)
            b(l,h; u=u0) = QuantityIntervalV1(ExactFiniteIntervalV1(l,h,false),u)
            axis = PeriodicAxisV1(1, NonnegativeQuantityV1(7,u0))
            chart = CoordinateChartGeneV1(ChartRefV1("chart"),CoordinateFrameRefV1("frame"),(b(-2,5),b(-3,4),b(-1,6)),(axis,),root("coord",2,cc,ambient),root("metric",7,cc,metric))
            chart2 = CoordinateChartGeneV1(ChartRefV1("chart2"),CoordinateFrameRefV1("other-frame"),(b(-2,5),b(-3,4),b(-1,6)),(),root("coord2",2,cc,ambient),root("metric2",7,cc,metric))
            transition = ChartTransitionMapGeneV1(ChartRefV1("chart"),ChartRefV1("chart2"),root("transition",9,cc,cc))
            support = SpatialSupportGeneV1(SpatialSupportRefV1("support"),3,(CoordinateFrameRefV1("frame"),CoordinateFrameRefV1("other-frame")),(chart,chart2), (transition,), NonnegativeQuantityV1(2,ulen))
            gene = FieldParameterGeneV1(FieldParameterRefV1("param"),u0,ParameterTransformSpecV1(transform_linear),b(-2,5),0.25)
            objects = (SpatialSupportRefV1("ref"), SpatialMultiIndex3V1(1,-2,3), ExactSpatialVector3V1((1//3,-2//5,7//11),u0), gene, root("root",1,cc,ambient), chart, transition, support)
            baseline1 = canonical_json(getfield(objects, 1)); baseline2 = canonical_hash(getfield(objects, 1)).value
            baseline3 = canonical_json(getfield(objects, 2)); baseline4 = canonical_hash(getfield(objects, 2)).value
            baseline5 = canonical_json(getfield(objects, 3)); baseline6 = canonical_hash(getfield(objects, 3)).value
            baseline7 = canonical_json(getfield(objects, 4)); baseline8 = canonical_hash(getfield(objects, 4)).value
            baseline9 = canonical_json(getfield(objects, 5)); baseline10 = canonical_hash(getfield(objects, 5)).value
            baseline11 = canonical_json(getfield(objects, 6)); baseline12 = canonical_hash(getfield(objects, 6)).value
            baseline13 = canonical_json(getfield(objects, 7)); baseline14 = canonical_hash(getfield(objects, 7)).value
            baseline15 = canonical_json(getfield(objects, 8)); baseline16 = canonical_hash(getfield(objects, 8)).value
            __DEFINITION__
            __TRIGGER__
            @assert HIT[]
            if !(baseline1 === canonical_json(getfield(objects, 1)) && baseline2 === canonical_hash(getfield(objects, 1)).value); println("MISMATCH1"); exit(3); end
            if !(baseline3 === canonical_json(getfield(objects, 2)) && baseline4 === canonical_hash(getfield(objects, 2)).value); println("MISMATCH2"); exit(3); end
            if !(baseline5 === canonical_json(getfield(objects, 3)) && baseline6 === canonical_hash(getfield(objects, 3)).value); println("MISMATCH3"); exit(3); end
            if !(baseline7 === canonical_json(getfield(objects, 4)) && baseline8 === canonical_hash(getfield(objects, 4)).value); println("MISMATCH4"); exit(3); end
            if !(baseline9 === canonical_json(getfield(objects, 5)) && baseline10 === canonical_hash(getfield(objects, 5)).value); println("MISMATCH5"); exit(3); end
            if !(baseline11 === canonical_json(getfield(objects, 6)) && baseline12 === canonical_hash(getfield(objects, 6)).value); println("MISMATCH6"); exit(3); end
            if !(baseline13 === canonical_json(getfield(objects, 7)) && baseline14 === canonical_hash(getfield(objects, 7)).value); println("MISMATCH7"); exit(3); end
            if !(baseline15 === canonical_json(getfield(objects, 8)) && baseline16 === canonical_hash(getfield(objects, 8)).value); println("MISMATCH8"); exit(3); end
            exit(0)
            """
            script = replace(script, "__DEFINITION__" => definition, "__TRIGGER__" => trigger)
            command = `$(Base.julia_cmd()) --startup-file=no --project=$(Base.active_project()) -e $script`
            result = try
                run(command); true
            catch err
                showerror(stderr, err, catch_backtrace()); println(stderr); false
            end
            result || println(stderr, "FAILED migration poison: ", definition, " / ", trigger)
            result
        end
        probes = (
            ("@eval Base.print(::IOBuffer,::String)=(HIT[]=true;nothing)", "Base.print(IOBuffer(),\"x\")"),
            ("@eval Base.:*(::String,::String)=(HIT[]=true;\"x\")", "Base.:*(\"a\",\"b\")"),
            ("@eval Base.:*(::String,::String,::String...)=(HIT[]=true;\"x\")", "Base.:*(\"a\",\"b\",\"c\")"),
            ("@eval Base.string(::Int64)=(HIT[]=true;\"x\")", "string(Int64(1))"),
            ("@eval Base.join(::Tuple,::AbstractString)=(HIT[]=true;\"x\")", "Base.join((1,2),\",\")"),
            ("@eval Base.repr(::Float64)=(HIT[]=true;\"x\")", "repr(1.0)"),
            ("@eval Base.getindex(::String,::Int)=(HIT[]=true;error(\"x\"))", "try \"x\"[1] catch; end"),
            ("@eval Base.iterate(::String,::Int)=(HIT[]=true;nothing)", "Base.iterate(\"x\",1)"),
            ("@eval Base.iterate(::Tuple,::Int)=(HIT[]=true;nothing)", "Base.iterate((1,),1)"),
            ("@eval Base.getindex(::NTuple{3,Int64},::Int)=(HIT[]=true;0)", "getindex((Int64(1),Int64(2),Int64(3)),1)"),
            ("@eval Base.getindex(::Vector{UInt8},::Int)=(HIT[]=true;0)", "UInt8[1][1]"),
            ("@eval Base.iterate(::Vector{Int},::Int)=(HIT[]=true;nothing)", "Base.iterate(Int[1],1)"),
            ("@eval Base.codeunits(::String)=(HIT[]=true;UInt8[])", "Base.codeunits(\"x\")"),
            ("@eval Base.ncodeunits(::String)=(HIT[]=true;0)", "Base.ncodeunits(\"x\")"),
            ("@eval Base.bytes2hex(::Vector{UInt8})=(HIT[]=true;\"x\")", "Base.bytes2hex(UInt8[1])"),
            ("@eval SHA.sha256(::Base.CodeUnits{UInt8,String})=(HIT[]=true;UInt8[])", "SHA.sha256(codeunits(\"x\"))"),
            ("@eval Base.hash(::String,::UInt)=(HIT[]=true;UInt(0))", "Base.hash(\"x\",UInt(0))"),
            ("@eval FusionConceptAI.canonical_json(::Any)=(HIT[]=true;\"x\")", "FusionConceptAI.canonical_json(1)"),
            ("@eval FusionConceptAI.canonical_hash(::Any)=(HIT[]=true;objects[1])", "FusionConceptAI.canonical_hash(1)"),
            ("@eval FusionConceptAI.semantic_view(::Any)=(HIT[]=true;\"x\")", "FusionConceptAI.semantic_view(1)"),
            ("@eval FusionConceptAI._g2_quote(::String)=(HIT[]=true;\"x\")", "FusionConceptAI._g2_quote(\"x\")"),
            ("@eval FusionConceptAI._g25_quote(::String)=(HIT[]=true;\"x\")", "FusionConceptAI._g25_quote(\"x\")"),
        )
        for probe_case in probes
            @test probe(probe_case[1], probe_case[2])
        end
    end
end
